name: Build and Deploy on gh-pages

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 跳过包含 [skip ci] 的 commit，防止死循环
      - name: Check commit message
        id: check_message
        run: |
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=%B >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Skip if commit message contains [skip ci]
        if: contains(steps.check_message.outputs.commit_message, '[skip ci]')
        run: echo "Skipping build because commit contains [skip ci]"
      
      - name: Build site
        if: "!contains(steps.check_message.outputs.commit_message, '[skip ci]')"
        run: |
          # 这里写你的构建命令，比如 npm install && npm run build
          echo "Build steps here"

      - name: Deploy to gh-pages branch
        if: "!contains(steps.check_message.outputs.commit_message, '[skip ci]')"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # 修改为你的构建产物目录
          commit_message: "Deploy site [skip ci]"
